[build]
  publish = "."
  command = "echo 'No build command'"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  included_files = ["node_modules/**"]

# Individual function settings
[functions.simple-ai]
  timeout = 90
  
[functions.api-health]
  timeout = 90

[build.environment]
  NODE_VERSION = "18"

# For local development
[dev]
  framework = "#static"
  command = "echo 'No dev command'"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 