[build]
  publish = "."
  command = "echo 'No build command'"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  included_files = ["node_modules/**"]

# Individual function settings
[functions.simple-ai]
  timeout = 90
  
[functions.api-health]
  timeout = 90
  
[functions.direct-api-test]
  timeout = 90

[functions.streaming-ai]
  timeout = 90

# Edge function for streaming
[[edge_functions]]
  path = "/api/streaming-ai"
  function = "streaming-ai"

# Test edge function
[[edge_functions]]
  path = "/api/test-edge"
  function = "test"
  
# Ensure edge functions can access environment variables
[context.production.environment]
  NETLIFY_EDGE_FUNCTIONS_ENABLED = "true"

[build.environment]
  NODE_VERSION = "18"

# For local development
[dev]
  framework = "#static"
  command = "echo 'No dev command'"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 